language: c
compiler: gcc
 
matrix:
  include:
  
    - os: linux
      dist: xenial
      arch: arm64
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - sourceline: 'ppa:ubuntu-toolchain-r/test'
            packages:
                - gcc-8
                - g++-8
                - linux-headers-$(uname -r)
      env:
        - CCOMPILER=gcc-8
        - CXXCOMPILER=g++-8

    - os: linux
      dist: xenial
      arch: amd64
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - sourceline: 'ppa:ubuntu-toolchain-r/test'
            packages:
                - gcc-8
                - g++-8
                - linux-headers-$(uname -r)
      env:
        - CCOMPILER=gcc-8
        - CXXCOMPILER=g++-8
        
    - os: linux
      dist: xenial
      arch: arm64
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - sourceline: 'ppa:ubuntu-toolchain-r/test'
            packages:
                - gcc-9
                - g++-9
                - linux-headers-$(uname -r)
      env:
        - CCOMPILER=gcc-9
        - CXXCOMPILER=g++-9
        
    - os: linux
      dist: xenial
      arch: amd64
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - sourceline: 'ppa:ubuntu-toolchain-r/test'
            packages:
                - gcc-9
                - g++-9
                - linux-headers-$(uname -r)
      env:
        - CCOMPILER=gcc-9
        - CXXCOMPILER=g++-9

    - os: linux
      dist: bionic
      arch: arm64
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - sourceline: 'ppa:ubuntu-toolchain-r/test'
            packages:
                - gcc-10
                - g++-10
                - linux-headers-$(uname -r)
      env:
        - CCOMPILER=gcc-10
        - CXXCOMPILER=g++-10
        
    - os: linux
      dist: bionic
      arch: amd64
      sudo: required
      addons:
        apt:
            update: true
            sources:
                - sourceline: 'ppa:ubuntu-toolchain-r/test'
            packages:
                - gcc-10
                - g++-10
                - linux-headers-$(uname -r)
      env:
        - CCOMPILER=gcc-10
        - CXXCOMPILER=g++-10

    - os: linux
      dist: bionic
      arch: arm64
      sudo: required
      addons:
        apt:
            update: true
            packages:
                - gcc
                - g++
                - linux-headers-$(uname -r)
      env:
        - CCOMPILER=gcc
        - CXXCOMPILER=g++
        
    - os: linux
      dist: bionic
      arch: amd64
      sudo: required
      addons:
        apt:
            update: true
            packages:
                - gcc
                - g++
                - linux-headers-$(uname -r)
      env:
        - CCOMPILER=gcc
        - CXXCOMPILER=g++

    - os: linux
      dist: focal
      arch: arm64
      sudo: required
      addons:
        apt:
            update: true
            packages:
                - gcc
                - g++
                - linux-headers-$(uname -r)
      env:
        - CCOMPILER=gcc
        - CXXCOMPILER=g++

    - os: linux
      dist: focal
      arch: amd64
      sudo: required
      addons:
        apt:
            update: true
            packages:
                - gcc
                - g++
                - linux-headers-$(uname -r)
      env:
        - CCOMPILER=gcc
        - CXXCOMPILER=g++
        
install:
  - if [[ -n "$CCOMPILER" ]]; then export CC=$CCOMPILER; fi
  - if [[ -n "$CXXCOMPILER" ]]; then export CXX=$CXXCOMPILER; fi
      
script:
  - uname -a
  - make
  - sudo insmod module/pteditor.ko
  - cd test
  - TRAVISCI=1 ./tests
