name: PTEditor Test
on: [push]
jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: uname -a
      - run: ls -hal
      - run: sudo apt install gcc g++ linux-headers-$(uname -r)
      - run: make && git diff --exit-code
      - run: sudo insmod module/pteditor.ko
      - run: ./test/tests
